coreos/fedora-coreos-cincinnati

.travis.yml, Cargo.lock, README.md, dumnati/Cargo.toml, dumnati/src/graph.rs, dumnati/src/main.rs, dumnati/src/metrics.rs, dumnati/src/scraper.rs
This updates to std::future, which also unlocks futures 0.3 and
async/await. Minimum support toolchain for this is now 1.39.0.
In order to perform the update, all other dependencies had to be
updated too: actix, actix-web, reqwest.
=> dumnati: update async logic to std::future

dumnati/src/main.rs
This enables scraping endpoints and serving metadata for the upcoming
'next' stream.
=> scraper: add 'next' stream

.travis.yml
This reworks the Travis setup and adds a new job taking care
of building via Dockerfile.
=> ci: build via Dockerfile in Travis

Cargo.lock, dumnati/Cargo.toml, dumnati/src/main.rs
This will allow JS logic hosted on builds.coreos.fedoraproject.org
to fetch the graph without triggering a browser error.
Closes: https://github.com/coreos/fedora-coreos-cincinnati/issues/17
=> dumnati: add CORS middleware 

dumnati/src/scraper.rs
This lowers the idle timeout on reqwest connection pool so that it
is lower than the S3/Cloudfront idle timeout (20s).
It should help avoiding races with the server closing an idle connection
in the pool, which at the same time has been selected for sending the
next request.
Ref: https://aws.amazon.com/premiumsupport/knowledge-center/s3-socket-connection-timeout-error/
=> scraper: lower connection idle timeout

Cargo.lock, Cargo.toml, commons/.gitignore, commons/Cargo.toml, commons/src/graph.rs, commons/src/lib.rs, commons/src/metadata.rs, commons/src/metrics.rs, commons/src/policy.rs, fcos-graph-builder/.gitignore, fcos-graph-builder/Cargo.toml, fcos-graph-builder/src/main.rs, fcos-graph-builder/src/scraper.rs, fcos-policy-engine/.gitignore, fcos-policy-engine/Cargo.toml, fcos-policy-engine/src/main.rs
This changes splits dumnati to two binaries and a library crate. No content changes are added and only directory structure changes.
Related: https://github.com/coreos/fedora-coreos-cincinnati/issues/3
Signed-off-by: Allen Bai <abai@redhat.com>
=> *: split dumnati to commons, graph-builder, and policy-engine

fcos-graph-builder/src/main.rs, fcos-policy-engine/src/main.rs
This separates ports used by fcos-* modules from ports used by dumnati.
fcos-graph-builder uses: 5050, 6060
fcos-policy-engine uses: 5051, 6061
dumnati uses: 8080, 8081, 9080, 9081
Signed-off-by: Allen Bai <abai@redhat.com>
=> fcos-*: use separate ports for fcos-* modules

README.md, dist/fedora-infra/Dockerfile
This moves the new graph-builder and policy-engine binaries to
/usr/local/bin/ too.
=> dockerfile: put all binaries in PATH

Cargo.lock, commons/Cargo.toml, commons/src/lib.rs, commons/src/web.rs, fcos-graph-builder/src/main.rs, fcos-policy-engine/src/main.rs
This adds a common helper for CORS logic and wires it into
graph-builder and policy-engine.
Ref: https://github.com/coreos/fedora-coreos-cincinnati/pull/18
=> commons: add CORS helper

Cargo.lock, fcos-policy-engine/Cargo.toml, fcos-policy-engine/src/main.rs, fcos-policy-engine/src/utils.rs
Removes previous empty dummy graph returned by `fcos-policy-engine` and fetches the graph from `fcos-graph-builder` instance, which is running under the same pod as `fcos-policy-engine`.
Also changes ports used by `fcos-*` such that they don't conflict with `dumnati` ports.
Related to: https://github.com/coreos/fedora-coreos-cincinnati/issues/3
Signed-off-by: Allen Bai <abai@redhat.com>
=> fcos-policy-engine: fetch graph from fcos-graph-builder instance

dumnati/src/main.rs, fcos-graph-builder/src/main.rs, fcos-policy-engine/src/utils.rs
This finalizes graph-builder swap, moving the new binary into
the original default port.
=> graph-builder: move to final default port

fcos-graph-builder/src/scraper.rs
This is a backport of https://github.com/coreos/fedora-coreos-cincinnati/pull/20 to the split graph-builder code.
---
This lowers the idle timeout on reqwest connection pool so that it
is lower than the S3/Cloudfront idle timeout (20s).
It should help avoiding races with the server closing an idle connection
in the pool, which at the same time has been selected for sending the
next request.
Ref: https://aws.amazon.com/premiumsupport/knowledge-center/s3-socket-connection-timeout-error/
=> graph-builder: lower connection idle timeout

dumnati/src/main.rs, fcos-policy-engine/src/main.rs
This finalizes policy-engine swap, moving the new binary into
the original default port.
=> policy-engine: move to final default port

fcos-graph-builder/src/main.rs, fcos-policy-engine/src/main.rs
This enables timestamping when printing log entries, as it is
otherwise difficult to locate recent events on a log stream.
=> main: print timestamp for log entries

dist/fedora-infra/Dockerfile
This updates the container base image to Fedora 33.
=> dist/Dockerfile: bump base image to Fedora 33

commons/src/web.rs, fcos-graph-builder/src/main.rs, fcos-graph-builder/src/settings.rs, fcos-policy-engine/src/main.rs, fcos-policy-engine/src/settings.rs
This tweaks CORS middleware in order to make the origin allowlist
optional. If no allowlist is provided, all origins are accepted.
=> commons/web: make CORS origin allowlist optional

dist/fedora-infra/Dockerfile
This updates the container base image to Fedora 34.
=> dist/Dockerfile: bump base image to Fedora 34

.github/workflows/containers.yml, .github/workflows/rust.yml, README.md
=> workflows: bump toolchain; restrict repository access

dist/fedora-infra/Dockerfile
This reverts commit c81254e4080f3187c5b7abf24ea92e84672725f4.
Ref: https://pagure.io/fedora-infrastructure/issue/10111#comment-746286
=> Revert "dist/Dockerfile: bump base image to Fedora 34"

commons/src/web.rs, fcos-graph-builder/src/main.rs, fcos-policy-engine/src/main.rs
This adds some logic in both graph-builder and policy-engine to validate
the scope of incoming graph requests (basearch and stream).
It also allows configuring filtering to a subset of allowed scopes,
which will be useful for gradually rolling out multi-arch support.
=> commons: add scope validation and filtering

fcos-graph-builder/src/main.rs, fcos-graph-builder/src/scraper.rs
This enhances graph-builder metrics, allowing to inspect access
patterns to cached graphs.
=> graph-builder: add metrics around cache requests

commons/src/graph.rs, fcos-graph-builder/src/main.rs, fcos-graph-builder/src/settings.rs
This adds graph-builder support for processing and caching 'aarch64' graphs.
Closes: https://github.com/coreos/fedora-coreos-cincinnati/issues/51
=> graph-builder: add scopes for all aarch64 streams

fcos-policy-engine/src/main.rs
This removes the hard-coded scopes filter, effectively allowing
queries for 'aarch64' basearch.
Closes: https://github.com/coreos/fedora-coreos-cincinnati/issues/52
=> policy-engine: remove scopes filter

commons/src/graph.rs, fcos-graph-builder/src/main.rs, fcos-graph-builder/src/scraper.rs
This tweaks the graph-builder scraping logic to directly cache the
already serialized JSON data. As the caches are already fully split
according to basearch/stream scope, there is no need to further
process graph data on each request.
=> graph-builder: cache graphs as already serialized data

dist/fedora-infra/Dockerfile
This updates the container base image to Fedora 35.
=> dist/Dockerfile: bump base image to Fedora 35

.github/workflows/rust.yml, Cargo.lock, commons/src/graph.rs
This refreshes the lockfile through `cargo update`, in order to shake
off stale versions that can be directly upgraded.
=> lockfile: update dependencies

Cargo.lock, fcos-graph-builder/Cargo.toml, fcos-policy-engine/Cargo.toml
This reverts commit d51bef47da9a0e11cb9ee1d5f2547f4614624e33.
We have to revert the `reqwest` portion of https://github.com/coreos/fedora-coreos-cincinnati/pull/75 due to `tokio` incompatibilities.
We will update that as the same time as we port to latest `actix-web`.
=> Revert "Added updated reqwest dependency"

fcos-graph-builder/src/settings.rs
FCOS is now publishing s390x streams.
=> graph-builder: add scopes for s390x

README.md
This is useful for other CoreOS members, but also for anyone curious to
see details of an example deployment.
=> docs: link to Fedora infra docs from README

Cargo.lock, fcos-graph-builder/Cargo.toml, fcos-graph-builder/src/cli.rs, fcos-graph-builder/src/main.rs, fcos-policy-engine/Cargo.toml, fcos-policy-engine/src/cli.rs, fcos-policy-engine/src/main.rs
This reworks CLI handling logic, porting to latest clap v3.
Closes: https://github.com/coreos/fedora-coreos-cincinnati/issues/85
=> cli: port CLI handling to clap v3

fcos-graph-builder/src/settings.rs
We are now shipping ppc64le on the FCOS stable stream.
=> graph-builder: add scopes for ppc64le for stable

commons/src/graph.rs, commons/src/metadata.rs, commons/src/policy.rs, commons/src/web.rs, fcos-graph-builder/src/main.rs, fcos-graph-builder/src/scraper.rs, fcos-graph-builder/src/settings.rs, fcos-policy-engine/src/main.rs, fcos-policy-engine/src/utils.rs
When parsing the release index, check for the new `oci-images` key. If
present, also build up a separate graph with only nodes containing OCI
information. In that case, the node payload is the pullspec and the
scheme declared in the node metadata is `oci`.
When a client requests a graph, check if the `oci=` URL parameter was
set. If so, return back the OCI graph instead of the OSTree one.
Part of https://github.com/coreos/fedora-coreos-tracker/issues/1823.
=> Add support for querying OCI graph

dist/fedora-infra/Dockerfile
Switch the builder stage from `registry.fedoraproject.org` to `quay.io/fedora/fedora:42` to align with common usage in container build workflows.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1851
=> Dockerfile: use quay.io as source for Fedora base image

commons/src/graph.rs, commons/src/metadata.rs
As part as [1] we want to have releases with only OCI images shipped. Make the commits optional so cincinnati will still build a graph if the ostree commit is missing.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1895
=> scraper: support releases without ostree commits
